# Generated by Django 3.0.2 on 2020-01-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200124_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_d_dob',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_d_lic_class',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_d_lic_exp',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_d_lic_num',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_first_name',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_last_name',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_phone',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_z_code',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_d_dob',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_d_lic_class',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_d_lic_exp',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_d_lic_num',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_first_name',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_last_name',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_phone',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_z_code',
        ),
    ]
