# Generated by Django 3.0.2 on 2020-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cc_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='customer',
            name='d_dob',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='customer',
            name='d_lic_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
