# Generated by Django 3.0.2 on 2020-01-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200124_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_01_email',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='additional_driver_02_email',
        ),
        migrations.AlterField(
            model_name='adobedriver',
            name='d_dob',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='adobedriver',
            name='d_lic_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='rental',
            name='additional_driver_01_d_dob',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='rental',
            name='additional_driver_01_d_lic_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='rental',
            name='additional_driver_02_d_dob',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='rental',
            name='additional_driver_02_d_lic_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='van',
            name='tag_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
