# Generated by Django 3.0.2 on 2020-01-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200124_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_d_dob',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_d_lic_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D-Operator')], max_length=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_d_lic_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_d_lic_num',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_01_z_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_d_dob',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_d_lic_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D-Operator')], max_length=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_d_lic_exp',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_d_lic_num',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rental',
            name='additional_driver_02_z_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
